### ISSUE TITLE
Implement Config Storage Manager class

### ISSUE THREAD

**Issue by andressadotpy** [andressadotpy/config-stash#1]
Implement a class to store configuration.

Acceptance Criteria:

**1. Environment Variable Configuration Loading:** 
   - The class should be able to load configurations from environment variables.

**2. Prefixed Environment Variable Configuration Loading:** 
   - The class should also support loading configurations from prefixed environment variables.

**3. File Configuration Loading:**
   - The capability to load configurations from a YAML file should be provided.

YAML file example
```yaml
url: "stage"
database: "db_address"
db_pass: "VAULT.vault_secret_path.vault_secret_key"
username: "ENV.USER"

cloudaccessdb:
  prefix_name: "cloud_db" 
  user: "cloud_access_user"
  host: "example.com"

cloud_access_db:
  port: 1111
  dbName: "cloud_access"
```

**4. Vault Configuration Loading:**
   - Additionally, loading configurations from a vault should be supported.
