### ISSUE TITLE
Implement system to load a YAML file

### ISSUE THREAD

**Issue by andressadotpy** [andressadotpy/config-stash#2]
Handles YAML in this format.

```yaml
url: "stage"
database: "db_address"
db_pass: "VAULT.vault_secret_path.vault_secret_key"
username: "ENV.USER"

cloudaccessdb:
  prefix_name: "cloud_db"
  user: "cloud_access_user"
  host: "example.com"

cloud_access_db:
  port: 2317
  dbName: "cloud_access"
```
